name: CI/CD Pipeline for Game Universe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test_and_deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Правильне налаштування для вказівки шляху до lock-файлу для кешування
          cache-dependency-path: ./game-universe/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./game-universe

      # Optional: Check code formatting with Prettier
      # Make sure you have "format:check": "prettier --check \"**/*.{ts,tsx,js,jsx,json,md}\"" in your package.json scripts
      # - name: Check Code Formatting
      #   run: npm run format:check
      #   working-directory: ./game-universe # Якщо розкоментуєте, додайте working-directory

      - name: Run ESLint
        run: npm run lint
        working-directory: ./game-universe

      - name: Run Tests with Coverage
        run: npm run test:coverage
        working-directory: ./game-universe

      - name: Build Project
        run: npm run build
        working-directory: ./game-universe
        env:
          NODE_ENV: production # Явно вказуємо продакшн середовище для збірки

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        working-directory: ./game-universe

      - name: Deploy to Vercel Production
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./game-universe

      - name: Run Lighthouse CI Audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: https://game-universe.vercel.app # Ваш продакшн URL для аудиту
#          minAutopassScore: 90
          # configPath: ./lighthouserc.json # Розкоментуйте, якщо ви використовуєте власну конфігурацію Lighthouse
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }} # Розкоментуйте, якщо ви надсилаєте звіти на LHCI сервер
