name: CI/CD Pipeline for Game Universe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test_and_deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./game-universe/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./game-universe

      - name: Run ESLint
        run: npm run lint
        working-directory: ./game-universe

      - name: Run Tests with Coverage
        run: npm run test:coverage
        working-directory: ./game-universe
        env:
          GITHUB_ID: ${{ secrets.GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Build Project
        run: npm run build
        working-directory: ./game-universe
        env:
          NODE_ENV: production
          GITHUB_ID: ${{ secrets.GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        working-directory: ./game-universe

      - name: Deploy to Vercel Production
        run: vercel deploy --prod --cwd=./game-universe --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_ID: ${{ secrets.GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Run Lighthouse CI Audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: https://game-universe.vercel.app